# Generated by Django 2.0.2 on 2018-03-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='czas rozpoczęcia')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='czas zakończenia')),
            ],
            options={
                'verbose_name_plural': 'gry',
                'verbose_name': 'gra',
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nazwa')),
                ('level', models.PositiveSmallIntegerField(default=50, help_text='Numeryczna wartość poziomu trudności. Im wyższa tym trudniej.', verbose_name='poziom')),
                ('can_cancel_last_move', models.BooleanField(default=False)),
                ('can_see_valid_moves', models.BooleanField(default=False)),
                ('can_see_threats', models.BooleanField(default=False)),
                ('can_see_hints', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'poziomy trudności',
                'verbose_name': 'poziom trudności',
            },
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Białe'), (2, 'Czarne')], default=1, verbose_name='kolor')),
                ('result', models.SmallIntegerField(blank=True, choices=[(1, 'Zwyciestwo'), (2, 'Remis'), (3, 'Porażka')], null=True, verbose_name='rezultat')),
                ('chessgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgames.ChessGame', verbose_name='gra')),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chessgames.DifficultyLevel', verbose_name='poziom trudności')),
            ],
            options={
                'verbose_name_plural': 'strony',
                'verbose_name': 'strona',
            },
        ),
    ]
