# Generated by Django 2.0.2 on 2018-03-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chessgames', '0001_initial'),
        ('chessplayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='side',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplayers.Player', verbose_name='gracz'),
        ),
        migrations.AlterUniqueTogether(
            name='side',
            unique_together={('player', 'chessgame'), ('color', 'chessgame')},
        ),
    ]
