# Generated by Django 2.0.2 on 2018-03-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chessgames', '0001_initial'),
        ('chessplayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='side',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='chessplayers.Player', verbose_name='gracz'),
        ),
    ]
