# Generated by Django 2.0.2 on 2018-03-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessgames', '0002_side_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='side',
            options={'verbose_name': 'strona', 'verbose_name_plural': 'strony'},
        ),
    ]
