# Generated by Django 2.0.2 on 2018-03-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessplayers', '0001_initial'),
        ('chessgames', '0003_auto_20180316_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='side',
            name='chessgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgames.ChessGame', verbose_name='gra'),
        ),
        migrations.AlterField(
            model_name='side',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplayers.Player', verbose_name='gracz'),
        ),
        migrations.AlterField(
            model_name='side',
            name='result',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Zwyciestwo'), (2, 'Remis'), (3, 'Porażka')], null=True, verbose_name='rezultat'),
        ),
        migrations.AlterUniqueTogether(
            name='side',
            unique_together={('player', 'chessgame'), ('color', 'chessgame')},
        ),
    ]
