# Generated by Django 2.0.2 on 2018-03-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chessgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chesspieces', to='chessgames.Side', verbose_name='strona')),
            ],
            options={
                'verbose_name': 'figura',
                'verbose_name_plural': 'figury',
            },
        ),
        migrations.CreateModel(
            name='ChessPieceMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='kiedy wykonany')),
                ('captured_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_by', to='chesslogic.ChessPiece', verbose_name='zbita figura')),
                ('moved_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chesslogic.ChessPiece', verbose_name='poruszona figura')),
            ],
            options={
                'verbose_name': 'ruch figury',
                'verbose_name_plural': 'ruchy figur',
            },
        ),
        migrations.CreateModel(
            name='ChessPieceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nazwa')),
                ('value', models.PositiveSmallIntegerField(default=1, verbose_name='wartość punktowa')),
            ],
            options={
                'verbose_name': 'rodzaj figury',
                'verbose_name_plural': 'rodzaje figur',
            },
        ),
        migrations.AddField(
            model_name='chesspiece',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chesslogic.ChessPieceType', verbose_name='typ'),
        ),
    ]
