# Generated by Django 2.0.2 on 2018-03-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessgames', '0002_auto_20180323_1212'),
        ('chesslogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesspiecemove',
            name='side',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chessgames.Side', verbose_name='strona wykonująca ruch'),
            preserve_default=False,
        ),
    ]
