# Generated by Django 2.0.2 on 2018-03-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chesslogic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'pola szachownic',
                'verbose_name': 'pole szachownicy',
            },
        ),
        migrations.AddField(
            model_name='chesspiecemove',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chesslogic.ChessField', verbose_name='docelowe pole'),
            preserve_default=False,
        ),
    ]
