# Generated by Django 2.0.2 on 2018-03-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessgames', '0003_auto_20180316_0930'),
        ('chesslogic', '0002_auto_20180316_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessfield',
            name='chessgame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chessgames.ChessGame', verbose_name='szachownica'),
            preserve_default=False,
        ),
    ]
