# Generated by Django 2.0.2 on 2018-03-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessgames', '0004_auto_20180316_1156'),
        ('chesslogic', '0003_chessfield_chessgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesspiece',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chesslogic.ChessField', verbose_name='położenie na szachownicy'),
        ),
        migrations.AlterField(
            model_name='chesspiece',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgames.Side', verbose_name='strona'),
        ),
        migrations.AlterField(
            model_name='chesspiecemove',
            name='moved_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chesslogic.ChessPiece', verbose_name='poruszona figura'),
        ),
        migrations.AlterUniqueTogether(
            name='chessfield',
            unique_together={('row', 'column', 'chessgame')},
        ),
    ]
