# Generated by Django 2.0.2 on 2018-03-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chesslogic', '0004_auto_20180316_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chessfield',
            unique_together=set(),
        ),
    ]
