# Generated by Django 2.0.2 on 2018-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessgames', '0004_auto_20180316_1156'),
        ('chesslogic', '0005_auto_20180316_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesspiecetype',
            name='id',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='chessfield',
            unique_together={('row', 'column', 'chessgame')},
        ),
    ]
