# Generated by Django 2.0.2 on 2018-03-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chesslogic', '0010_auto_20180316_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesspiece',
            name='initial_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initially_occupied_by', to='chesslogic.ChessField', verbose_name='położenie na szachownicy'),
        ),
    ]
